name: JS tests

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: bahmutov/npm-install@v1
    - name: Install yarn
      run: yarn
    - name: ESLint
      run: yarn lint:ci
    - name: Jest
      run: yarn test:ci
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required